name: rwhg-env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - alembic=1.15.2
  - annotated-types=0.7.0
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.6.15
  - catalogue=2.0.10
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpathlib=0.21.0
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorlog=6.9.0
  - comm=0.2.2
  - confection=0.1.5
  - contourpy=1.3.1
  - cpython=3.11.11
  - cycler=0.11.0
  - cymem=2.0.11
  - cython-blis=1.0.1
  - debugpy=1.8.13
  - decorator=5.2.1
  - einops=0.8.1
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.13.3
  - gflags=2.2.2
  - glog=0.5.0
  - greenlet=3.1.1
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - langcodes=3.4.1
  - language-data=1.3.0
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.12.1
  - libdeflate=1.22
  - libevent=2.1.12
  - libffi=3.4.4
  - libgrpc=1.71.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - liblapack=3.9.0
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.5
  - llvmlite=0.44.0
  - lz4-c=1.9.4
  - mako=1.3.10
  - marisa-trie=1.2.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - murmurhash=1.0.10
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nltk=3.9.1
  - nodejs=20.17.0
  - numba=0.61.2
  - numexpr=2.10.1
  - numpy=2.2.4
  - numpy-base=2.2.4
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.5.0
  - optuna=4.3.0
  - orc=2.1.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=4.3.7
  - preshed=3.0.9
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pyaml=20.4.0
  - pyarrow=19.0.0
  - pycparser=2.22
  - pydantic=2.11.2
  - pydantic-core=2.33.1
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2024.1
  - pywin32=307
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - re2=2024.07.02
  - regex=2024.11.6
  - requests=2.32.3
  - rich=14.0.0
  - scikit-learn=1.6.1
  - scikit-optimize=0.10.2
  - scipy=1.15.2
  - setuptools=72.1.0
  - shap=0.47.2
  - shellingham=1.5.4
  - six=1.17.0
  - slicer=0.0.8
  - smart-open=7.1.0
  - smart_open=7.1.0
  - snappy=1.2.1
  - spacy=3.8.5
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlalchemy=2.0.40
  - sqlite=3.45.3
  - srsly=2.5.1
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - tbb=2021.13.0
  - thinc=8.3.2
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.15.2
  - typer-slim=0.15.2
  - typer-slim-standard=0.15.2
  - typing-extensions=4.13.1
  - typing-inspection=0.4.0
  - typing_extensions=4.13.1
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wasabi=1.1.3
  - wcwidth=0.2.13
  - weasel=0.4.1
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - wrapt=1.17.2
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - de-core-news-sm==3.8.0
      - filelock==3.18.0
      - fsspec==2025.3.2
      - gower==0.1.2
      - huggingface-hub==0.30.2
      - mpmath==1.3.0
      - safetensors==0.5.3
      - sentence-transformers==4.1.0
      - sympy==1.13.1
      - tokenizers==0.21.1
      - torch==2.6.0
      - transformers==4.51.3
